### ISSUE TITLE
SystemError: <method 'get' of 'dict' objects> returned a result with an error set

### ISSUE THREAD

**Issue by pydevd** [mopemope/meinheld#101]
This error appears in the Docker with Django DRF application.

```python
Traceback (most recent call last):   File "/usr/local/lib/python3.7/site-packages/meinheld/mlogging.py", line 187, in _access     'h': environ.get('REMOTE_ADDR', '-'), SystemError: <method 'get' of 'dict' objects> returned a result with an error set
```

**Comment by kourge-ch** [comment]
I'm facing a similar issue, with a timeout. I'm running a Flask app with Gunicorn and Meinheld.

```
meinheld.server.timeout: timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meinheld/mlogging.py", line 187, in _access
    'h': environ.get('REMOTE_ADDR', '-'),
SystemError: <method 'get' of 'dict' objects> returned a result with an error set
```
