### ISSUE TITLE
Please support Gunicorn 20

### ISSUE THREAD

**Issue by hongquan** [mopemope/meinheld#115]
Using meinheld 1.0.2 with Gunicorn 20.0.4, I got this error:

```
ERROR 2020-07-25 00:02:21,426 mlogging 32489 140442800424768 AttributeError: __call__
```

**Comment by hongquan** [comment]
Actually, this was #101

**Comment by hongquan** [comment]
More log:

```
Jul 26 11:19:59 farmb-vinix gunicorn[2574]: [2020-07-26 11:19:59 +0700] [2641] [ERROR] Traceback (most recent call last):
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:   File "/home/web/TraiNamThang/venv/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 350, in run
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:     self.wait(sleep_time)
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:   File "/home/web/TraiNamThang/venv/lib/python3.7/site-packages/eventlet/hubs/poll.py", line 77, in wait
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:     time.sleep(seconds)
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:   File "/home/web/TraiNamThang/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 201, in handle_abort
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:     sys.exit(1)
Jul 26 11:19:59 farmb-vinix gunicorn[2574]: SystemExit: 1
Jul 26 11:19:59 farmb-vinix gunicorn[2574]: The above exception was the direct cause of the following exception:
Jul 26 11:19:59 farmb-vinix gunicorn[2574]: Traceback (most recent call last):
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:   File "/home/web/TraiNamThang/venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 130, in __call__
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:     set_script_prefix(get_script_name(environ))
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:   File "/home/web/TraiNamThang/venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 175, in get_script_name
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:     script_url = get_bytes_from_wsgi(environ, 'SCRIPT_URL', '') or get_bytes_from_wsgi(environ, 'REDIRECT_URL', '')
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:   File "/home/web/TraiNamThang/venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 196, in get_bytes_from_wsgi
Jul 26 11:19:59 farmb-vinix gunicorn[2574]:     value = environ.get(key, default)
Jul 26 11:19:59 farmb-vinix gunicorn[2574]: SystemError: <method 'get' of 'dict' objects> returned a result with an error set
```

**Comment by hongquan** [comment]
Explanation about "returned a result with an error set"

https://stackoverflow.com/questions/53796264/systemerror-class-int-returned-a-result-with-an-error-set-in-python

Some places in meinheld code violates these requirements:

https://github.com/mopemope/meinheld/blob/6ddb22b52783d22ba15c6cdfbcbc9ed05b5c0c46/meinheld/server/server.c#L1729-L1731
