### ISSUE TITLE
Encoding issue while uploading file in django application

### ISSUE THREAD

**Issue by HiddenFox** [mopemope/meinheld#62]
I have tested all the scenarios when my django application run without meinheld, and there is no exception.
But exceptions occurs if application is run by meinheld.

## Senario 1
The uploaded file is just a text file. It is wired that I uploaded a file of size 200kb successfully. Then I copy the content of this file and paste to double its size. The exception occurred when the second file is uploaded. 

I tried to debug and found that function 'meinheld.input.read' returns a str which cannot concat to bytes.

The call stack is:
```
Traceback (most recent call last):
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dev/d5_django_server/apps/product/admin.py", line 129, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 106, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/middleware/csrf.py", line 174, in process_view
    request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 137, in _get_post
    self._load_post_and_files()
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/request.py", line 260, in _load_post_and_files
    self._post, self._files = self.parse_file_upload(self.META, data)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/request.py", line 225, in parse_file_upload
    return parser.parse()
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 149, in parse
    for item_type, meta_data, field_stream in Parser(stream, self._boundary):
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 626, in __iter__
    for sub_stream in boundarystream:
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 439, in __next__
    return LazyStream(BoundaryIter(self._stream, self._boundary))
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 466, in __init__
    unused_char = self._stream.read(1)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 337, in read
    out = b''.join(parts())
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 330, in parts
    chunk = next(self)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 352, in __next__
    output = next(self._producer)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 414, in __next__
    data = self.flo.read(self.chunk_size)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/request.py", line 292, in read
    return self._stream.read(*args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 57, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
TypeError: can't concat bytes to str
```

## Senario 2
When a jpg is uploaded, the exception is different. 

The call stack is:
```
Traceback (most recent call last):
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dev/d5_django_server/apps/product/admin.py", line 129, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 106, in _wrapped_view
    result = middleware.process_view(request, view_func, args, kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/middleware/csrf.py", line 174, in process_view
    request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 137, in _get_post
    self._load_post_and_files()
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/request.py", line 260, in _load_post_and_files
    self._post, self._files = self.parse_file_upload(self.META, data)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/request.py", line 225, in parse_file_upload
    return parser.parse()
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 149, in parse
    for item_type, meta_data, field_stream in Parser(stream, self._boundary):
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 626, in __iter__
    for sub_stream in boundarystream:
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 439, in __next__
    return LazyStream(BoundaryIter(self._stream, self._boundary))
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 466, in __init__
    unused_char = self._stream.read(1)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 337, in read
    out = b''.join(parts())
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 330, in parts
    chunk = next(self)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 352, in __next__
    output = next(self._producer)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/multipartparser.py", line 414, in __next__
    data = self.flo.read(self.chunk_size)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/http/request.py", line 292, in read
    return self._stream.read(*args, **kwargs)
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 57, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
  File "/home/dev/virtualenv/python3/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 45, in _read_limited
    result = self.stream.read(size)
  File "/home/dev/virtualenv/python3/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1412: invalid start byte
```

**Comment by HiddenFox** [comment]
My site-packages:
```
boto==2.38.0
Django==1.8.2
django-appconf==1.0.1
django-debug-toolbar==1.3.0
django-filter==0.10.0
django-grappelli==2.7.1
django-imagekit==3.2.6
django-ipware==1.1.0
django-storages-redux==1.2.3
djangorestframework==3.1.3
greenlet==0.4.9
gunicorn==19.3.0
meinheld==0.5.7
mysqlclient==1.3.6
pilkit==1.1.12
Pillow==2.9.0
six==1.9.0
sqlparse==0.1.15
wheel==0.24.0
```

**Comment by methane** [comment]
Could you try #63 ?

**Comment by HiddenFox** [comment]
@methane Thanks for your response. 
I tried this patch by: 
1. Clone the latest code from github. 
2. Modify server.c according to the commit. 
3. python setup.py install

And I got another exception every time a form is committed. Even if the form has no file to be posted.
I am not sure if it is caused by the change or my incorrect installation.

Here is the exception:
```
Traceback (most recent call last):
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/han/workspace/d5/d5_django_server/apps/product/admin.py", line 129, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1466, in changeform_view
    if all_valid(formsets) and form_validated:
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/formsets.py", line 439, in all_valid
    if not formset.is_valid():
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/forms/models.py", line 430, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/db/models/base.py", line 1125, in full_clean
    self.clean_fields(exclude=exclude)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/db/models/base.py", line 1167, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 589, in clean
    self.run_validators(value)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 541, in run_validators
    v(value)
  File "/home/han/workspace/d5/d5_django_server/d5/files/validator.py", line 53, in __call__
    actual_size = file_obj.file.size
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/db/models/fields/files.py", line 51, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/django/core/files/storage.py", line 37, in open
    return self._open(name, mode)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/storages/backends/s3boto.py", line 388, in _open
    f = self.file_class(name, mode, self)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/storages/backends/s3boto.py", line 103, in __init__
    self.key = storage.bucket.get_key(self._storage._encode_name(name))
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/boto/s3/bucket.py", line 192, in get_key
    key, resp = self._get_key_internal(key_name, headers, query_args_l)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/boto/s3/bucket.py", line 199, in _get_key_internal
    query_args=query_args)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/han/workspace/python/env/python3/lib/python3.4/site-packages/boto/connection.py", line 943, in _mexe
    request.body, request.headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    server_hostname)
TypeError: _wrap_socket() argument 1 must be _socket.socket, not SSLSocket
```

**Comment by HiddenFox** [comment]
@methane It works well. Thank you!

**Comment by HiddenFox** [comment]
@methane When will this hotfix be published onto pypi? It is not so convenient to apply it to every environment manually.

**Comment by methane** [comment]
@mopemope Could you release new bugfix version?
Or may you give me a right to make a release on PyPI?

**Comment by mopemope** [comment]
@HiddenFox  @methane v0.5.8 released.
https://pypi.python.org/pypi/meinheld/0.5.8

**Comment by HiddenFox** [comment]
@mopemope Got it. Thanks very much.
